### ISSUE TITLE
tensorflow-gpu support

### ISSUE THREAD

**Issue by CSU-NXY** [jmaces/keras-adf#3]
Hi,

Thanks for your implementation of ADF network.

I'm tring to install with `pip install keras-adf`. But it starts downloading tensorflow-1.15 even if I've installed tensorflow1.15-gpu by myself. Does keras-adf support tensorflow-gpu?

**Comment by jmaces** [comment]
Yes, our implementation supports tensorflow-gpu. In fact, we used the GPU version in our own projects.

Unfortunately this does not seem to be recognized by the requirements specified for `pip`. Thank you for pointing out the issue. The problem is that it is not possible to specify one of two possible packages (tensorflow **or** tensorflow-gpu) as requirements on PyPI, see also https://github.com/tensorflow/tensorflow/issues/7166.

I will incorporate one of the recommended fixes discussed in https://github.com/tensorflow/tensorflow/issues/7166 in the next version. Until then you could try to download from github instead of installing from `pip`.

**Comment by CSU-NXY** [comment]
HI, jmaces

Thank you. I modified `INSTALL_REQUIRES` in `setup.py` from `tensorflow` to `tensorflow-gpu`, then everything works fine for me.

**Comment by CSU-NXY** [comment]
By the way, is it possible to use keras-adf to train a whole optical flow estimation network and get uncertainty map like Jochen et al. did in _Lightweight Probabilistic Deep Networks_?

**Comment by jmaces** [comment]
I am not very familiar with the detailed architecture of optical-flow estimation networks. But as long as the architecture only uses the basic building blocks provided by `keras-adf`it should be possible.

**Comment by CSU-NXY** [comment]
Thanks.
